# Generated by Django 3.1.4 on 2021-01-02 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='site',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crawler.site'),
        ),
    ]
