# Generated by Django 3.1.4 on 2021-01-16 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_auto_20210102_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawler.site'),
        ),
    ]
